###
GET http://localhost:8080/

###
GET http://localhost:8080/products

###
GET http://localhost:8080/products?page=0

###
GET http://localhost:8080/products?page=1

###
GET http://localhost:8080/products?page=2

###
GET http://localhost:8080/products?page=-1

###
GET http://localhost:8080/products?page=100

###
GET http://localhost:8080/products?min_price=9&max_price=11

###
GET http://localhost:8080/products?min_price=0&max_price=1000&page=1

###
GET http://localhost:8080/products?category=men's clothing

###
GET http://localhost:8080/products?category=men's clothing&page=1

###
GET http://localhost:8080/products/1

###
GET http://localhost:8080/products/14

###
GET http://localhost:8080/products/11

###
GET http://localhost:8080/products/14

###
GET http://localhost:8080/products/100

###
GET http://localhost:8080/products/-1
